This directory is placed placed directly in  =.emacs.d=, as it now uses emacs-starter-kit 2.0.

I am also bundling =eudcb-notmuch.el=, since its original repo went down.

* File/directory structure
The structure is currently something like this:
- =mail.el=: mail-related hacks mostly (now based on notmuch).
- =sync-com.el=: stuff for IRC/Jabber (now based on jabber-el and ii-mode).
+- =secrets.el=: wrapper code to load the actual, encrypted password variables using EasyPG+ (not used anymore).
- =.conkeror.rc=: not directly emacs-related. It's my (very hacky -- javascript isn't my thing) configuration file for Conkeror. However, it's so integrated in my Emacs workflow, I felt it deserved inclusion.
- =init.el=: everything else.

** Libraries bundled for convenience
- =eudc-notmuch.el=: notmuch bindings for, uh, address completion, included because the original repository went down.
- =org-notmuch.el=: included because I found it in a mail at the notmuch mailing list: it wasn't hosted on-line anywhere I (or, say el-get) could find it.
- =smart-quotes.el=: a small function to handle guillemets (»french quotes«) automatically. Actually written by [[http://idiomdrottning.org/][a friend]].

* Wishlist
- [X] GPG signature verification for notmuch. +I know somebody's working on it, it's just not in mainline notmuch yet.+ Yay, it's implemented! :)
- [ ] org-address interaction for notmuch
